### PR TITLE
Add Dashboard icon to header

### PR DESCRIPTION
**Pull request by deeola**
Added a dashboard icon from the specified website.

### CODE REVIEW

**Comment by AlexanderPuhl** [comment]
Hallo @deeola! Sorry this project has stalled quite a bit in the last month, I think we're ready to merge this pull request though but it has a conflict in the Header.jsx component. Would you be interested in resolving this and pushing it back up? If not we can take over. Either way we really do appreciate the contribution!

**Comment by deeola** [comment]
Hello, can you give me until morning to do that. I use CET and it's quite late here in Germany, is it okay if I do that in the morning?

**Comment by AlexanderPuhl** [comment]
Ya that will work for sure! This isn't blocking anything and there is no rush. Take your time!

**Comment by AlexanderPuhl** [comment]
Hey @deeola , I went ahead and took some of your code and finished off issue #39 , I really do appreciate the help man. Gonna close this issue since it's a duplicate.

**Pull request closed without merging**
